### ISSUE TITLE
The fireEvent.press event does not work as a result of the render function.

### ISSUE THREAD

**Issue by speackme** [callstack/react-native-testing-library#1198]
The fireEvent.press event does not work as a result of the render function.

When doing a console.log of the rendering element, it is seen that the Pressable instead of having the onPress event, it converts it to an onClick.

In the logic of the code, therefore, it is not correct.

```
const {getByTestId} = render(
    <Pressable
      onPress={() => { console.log('Press') }}
      testID="press"
    />,
  );

  console.log(getByTestId('press').props);

//////////////////////////
{
        testID: 'press',
        onBlur: [Function: onBlur],
        onFocus: [Function: onFocus],
        onStartShouldSetResponder: [Function: onStartShouldSetResponder] {
          testOnly_pressabilityConfig: [Function (anonymous)]
        },
        onResponderGrant: [Function: onResponderGrant],
        onResponderMove: [Function: onResponderMove],
        onResponderRelease: [Function: onResponderRelease],
        onResponderTerminate: [Function: onResponderTerminate],
        onResponderTerminationRequest: [Function: onResponderTerminationRequest],
        onClick: [Function: onClick],
        accessible: true,
        focusable: true,
        children: []
}


 npmPackages:
    @testing-library/react-native: ^11.2.0 => 11.2.0 
    react: 17.0.1 => 17.0.1 
    react-native: ^0.63.1 => 0.63.4 
    react-test-renderer: ^17.0.1 => 17.0.2

**Comment by pierrezimmermannbam** [comment]
This is the intended behavior, queries by testId return native components, and Pressable will render a View with an onClick prop as native component. The idea is that native components (host components) are the ones that are actually rendered and that's why it makes more sense to interact with them, rather than the function components (composite components). Some queries return presently composite components (byText, byPlaceholderText and byDisplayValue) but it should change soon to have a more consistent behavior (see the discussion in #1132). 

This should however not be an issue if you don't interact directly with the props of the component returned by your query but instead use fireEvent.press to click on your button. For other use cases such as checking wether an element is disabled or not, I recommend to use the matchers from [@testing-library/jest-native](https://github.com/testing-library/jest-native). 

This is a bit complicated and I'm not sure my explanation is clear so feel free to ask if you have any further questions, hope this helps !

**Comment by mdjastrzebski** [comment]
@speackme I've adapted your code as a test and it works fine under the current versions of RNTL & RN:

```tsx
test('fireEvent.press work fine', () => {
  const handlePress = jest.fn();
  const { getByTestId } = render(
    <Pressable onPress={handlePress} testID="press" />
  );
  fireEvent.press(getByTestId('press'));
  expect(handlePress).toHaveBeenCalledTimes(1);
});
```

Could you clarify what is the issue your facing?
