### ISSUE TITLE
Call for maintainers: Flow types

### ISSUE THREAD

**Issue by AugustinLF** [callstack/react-native-testing-library#1208]
## Describe the Feature
Currently we're maintaing flow types in the repo. We're not testing them in anyway (they could be broken), and I do see them as something not convenient for contribution, since it's most of the time missed by contributors, and for more complex types, it could even be a problem.

Flow is not targeting open source anymore, and even RN now by default suggest TS, see https://github.com/facebook/react-native/pull/35165.

We could move this maintenance to the community by moving it to https://github.com/flow-typed/flow-typed, and then, if there's  still a need, people could maintain it over there.

That would be a breaking change, so we'll need to time the release.

What do you think?

**Comment by mdjastrzebski** [comment]
I support the idea idea. Let's drop them in v12. None of the maintainers seems to be using Flow, so it became something we try to maintain but we don't really know if it's actually working. 

I think we should actually drop Flow types without moving them to FlowTyped by ourselves because we are equality unqualified to support them either here or there. We would announce that we are looking for somebody to maintain them to gauge the interest.

**Comment by AugustinLF** [comment]
That sounds ok to me, people could still copy our definitions and add them there if needed. Might be good though to have another minor release before that.

**Comment by mdjastrzebski** [comment]
We will probably have at least one minor release with #1064 and maybe #1191 if that would be ready. After that I think we should do all the planned breaking changes: #1208, #1184, #1180, #1132, maybe #1130 and release them together as v14.

**Comment by thymikee** [comment]
I asked on Twitter: https://twitter.com/thymikee/status/1588145699304218624. Please share if you can and let's see what at least a part of our user base thinks about it

**Comment by mdjastrzebski** [comment]
We've got 41 answers to @thymikee survey so far:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/6368606/200025460-047bf4f6-2bf6-4755-82f4-0de443f7b260.png">

Seems like around 22% users who voted still favour supporting Flow in some form. I think this percent might be inflated due to vocal minority of Flow users voicing their concern, while many TS users might ignore it as not relevant to them, but it's still somewhat sizeable part.

I was thinking about moving to Flow Typed idea, and concluded that unless we find someone dedicated to maintain the typings it will at first become a bigger burden for us due to two repos/two releases/etc, which will lead to FT typings becoming abandonware.

I suspect that finding a dedicated FT maintainer might not be easy, as the Flow community seems to shrink from day to day.

**Comment by mdjastrzebski** [comment]
@AugustinLF @thymikee wdyt? Should we do something regarding flow types?

**Comment by AugustinLF** [comment]
It'd be nice to do it, and shouldn't be too hard. But I don't know if anyone feels like doing so^^'

I'm short on time right now and I barely can review the PRs in the repo, so I can't do it in the upcoming weeks.

**Comment by thymikee** [comment]
I believe we should pause this until we find someone from the community to maintain the types. I suggest rename this to "Call for Flow types maintainer" and ideally create a corresponding issue in flow-typed repo
