### ISSUE TITLE
ByText queries don't seem to match across multiple Text elements

### ISSUE THREAD

**Issue by leepowelldev** [callstack/react-native-testing-library#1221]
Give this test:
```
import React from 'react';
import { screen, render } from '@testing-library/react-native';
import { Text, View } from 'react-native';

function MyComponent() {
  return (
    <View>
      <Text>Hello</Text>
      <Text>World</Text>
    </View>
  );
}

it('renders correctly', async () => {
  render(<MyComponent />);
  const text = screen.getByText('Hello World');
  expect(text).toBeTruthy();
});
```
I would expect the test to pass, according to the docs the `Text` elements should be joined together. I've tried various permutations (regex's, non-exact match, extra Text with a space) and nothing seems to match.

## Expected behavior

Test should pass

## Steps to Reproduce

Run simple test as above (I can put in a repo if it helps)

## Screenshots

<img width="698" alt="Screenshot 2022-11-10 at 15 09 06" src="https://user-images.githubusercontent.com/602052/201131792-6c229657-608e-4721-9fee-94f2a770ad78.png">

## Versions
npmPackages:
    @testing-library/react-native: ^11.4.0 => 11.4.0 
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-test-renderer: 18.1.0 => 18.1.0

**Comment by mdjastrzebski** [comment]
The behaviour is party correct. In my opinion it should behave in this way if `Text` elements are separate. The issue is however that it should match if in following case:

```ts
function MyComponent() {
  return (
    <Text>
      <Text>Hello</Text>
      <Text>World</Text>
    </Text>
  );
}
```

However it does not, and this is the bug that we should fix.

As a temporary workaround I can suggest using some other query + `toHaveTextContent` matcher from Jest Native.

**Comment by leepowelldev** [comment]
Sure, it's just we're in the middle of a upgrade and lots of our tests are now breaking on this one.

**Comment by mdjastrzebski** [comment]
Understood, I cannot promise any fix date for that bug, as proper text matching subject is more complex than it looks at first glance, we had couple of back and forth changes in the implementation, and we are ware around introducing potential breaking changes to other users.

If you have interest in this issue and some spare time I invite to provide a PR for that issue. Otherwise, changing query type and/or changing app structure to put string content into single `Text` instead of separate one might be the fastest workaround.

**Comment by mdjastrzebski** [comment]
The reason why current implementation is not recursive, is that in following example:

```ts
 <Text testID="outer-text">
    <Text testID="text-1">Hello</Text>
    <Text testID="text-2">World</Text>
  </Text>
```

recursive query for `Hello` will match both `text-1` and `outer-text`. A proper implementation should match only `text-1`, while in case of querying for `Hello World` it should match `outer-text`. That leads to implementation that match given `Text` element, only if none of its children is matched. So the current simple `findAll` tree walking algorithm is insufficient.

**Comment by mdjastrzebski** [comment]
@leepowelldev v11.5.0 contains a fix for matching nested `Text` content.

 It should work with:
```ts
<Text>
  <Text>Hello</Text>
  <Text>World</Text>
</Text>
```

but not with
```ts
<View>
  <Text>Hello</Text>
  <Text>World</Text>
</View>
```
