### ISSUE TITLE
Match issue when navigating between screens in a navigation stack

### ISSUE THREAD

**Issue by Alaa-Ben** [callstack/react-native-testing-library#1250]
## Describe the bug

Not sure whether this is a bug or intended: When navigating from a ScreenA to a ScreenB - so we're currently on ScreenB - (using react-navigation for example), the queries API matches all screens, including elements from ScreenA.
Is this intended ? i find it kinda weird, especially in cases where in both screens, there is for example an element with the same text.

## Expected behavior

Matchers should only match with the current screen on the stack

## Steps to Reproduce

Just a classic
```    render(
      <NavigationContainer>
        <Stack.Navigator screenOptions={screenOptions}>
          <Stack.Screen name="ScreenA" component={ScreenA} />
          <Stack.Screen name="ScreenB" component={ScreenB} />
        </Stack.Navigator>
      </NavigationContainer>
    )
```
then fireEvent some navigation button on ScreenA which will trigger the navigation.
Finally, match something on ScreenA (even though we're in ScreenB) and the match will still work.

## Versions
    @testing-library/react-native: ^11.5.0 => 11.5.0 
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-test-renderer: 18.1.0 => 18.1.0

**Comment by mdjastrzebski** [comment]
Awesome question @Alaa-Ben! This is indeed the default behaviour of RNTL as the element tree contains all screens back in the navigation stack and/or inactive tabs. These "invisible" elements are marked as hidden from accessibility.

You can configure RNTL to only match elements on the current page. You can do that in two ways:
1) Globally by calling `configure({ defaultIncludeHiddenElements: false })` in your Jest setup file - [details here](https://callstack.github.io/react-native-testing-library/docs/api/#defaultincludehiddenelements-option)
2) Per que query using `includeHiddenElements: false` query option - [details here](https://callstack.github.io/react-native-testing-library/docs/api-queries#includehiddenelements-option)

This option will become a default in the next major release, but since adding it would be a breaking change requiring a major release we will bundle it in the coming weeks or months with other useful but breaking changes. Till then we recommend you to enable it using the `configure({ defaultIncludeHiddenElements: false })` setting above.

**Comment by Alaa-Ben** [comment]
Perfect, thanks !
