### ISSUE TITLE
feat: Ability to fire generic events into the screen from the test

### ISSUE THREAD

**Issue by benjaminkay93** [callstack/react-native-testing-library#1354]
## Describe the Feature
Recently we where trying to find a lightweight way to mock our web sockets and couldn't find an easy way to do this in the current testing library without spinning up a mock server but that requires network connections to be mocked and thats not really what we were going for in our unit tests.

(Note for anyone looking for how to do this now: We ended up putting a Button in the screen that we use the fireEvent press functionality and the button fires the correct function inside the screen for us to mock this out... openly admit its a hacky work around)

What would be nice would be some kind of event function that can be called in the test and then trigger an event that can be listened to inside of an app (or mocked socket provider like we where doing)

e.g.
``` javascript
import { render, event, screen } from '@testing-library/react-native`
import React, { useEffect, useState } from 'react'
const Component = () => {
  const [name, setName] = useState('World')

  useEffect(() => {
    const listener = screen.addEventListener('some-event-name', data => {
      setName(data.newName)
    })
    return () => listener.removeEventListener()
  })

  return <Text testId="test-id">Hello, {name}!</Text>
}

test('app listens to event', async () => {
  render(<Component />)

  const text = await screen.getByTestId('test-id')
  expect(text).toBe('Hello, World!')

  await event('some-event-name', { newName: 'Dave' })

  const newText = await screen.getByTestId('test-id')
  expect(newText).toBe('Hello, Dave!')
})

```

## Possible Implementations
Honestly, I'm not sure how to accomplish this. I'm guessing theres already channels for communicating test events because of fireEvent so maybe a 'new' event on there that allows generic information to be passed, the above example isn't one that needs to be the final implementation ofc just to get a flavour.

## Related Issues
None that i've seen, will update this as and when necessary

**Comment by mdjastrzebski** [comment]
@benjaminkay93 The root issue here is that there seems to be no good package for mocking WebSockets. That leave you with couple of option on how to test it:

1. Mock WebSockets by yourself, but it might be hard to exactly replicate their behaviour
2. Mock some higher-level wrapper around WebSocket code.
3. Create your own WebSocket server (e.g. in node.js) that you will use for testing purposes. This is probably the most difficult path but also most realistic. You could a capability to send special "commands" to the web socket, so that it will respond with given payload. 

Getting to your question about firing events, we have `fireEvent` which might solve your need. It can fire a custom events, but you need to pass it a React element from which it will look for event handler. It will traverse the element tree up (going from passed element to all of it ancestors) until it find a matching event handler.

You can read more details here: https://callstack.github.io/react-native-testing-library/docs/api#fireevent

**Comment by mdjastrzebski** [comment]
Closing as non-actionable.
