### ISSUE TITLE
element should be considered hidden if opacity is 0

### ISSUE THREAD

**Issue by Niryo** [callstack/react-native-testing-library#1383]
## Describe the bug

Currently, we consider an element to be hidden if it has `display: none` in its style. we need to improve this logic by considering also `opacity:0` and maybe even `transform.scale: 0`.
also, we should probably improve the error message in such cases, because it could be confusing if you print the tree and see that the element is there, but the query fails because one of its parent has `opacity:0`

## Expected behavior

element with `opacity:0` should be considered to be hidden

## Steps to Reproduce

create an element with `opacity: 0` in its style, the element is not visible in the app, but will be visible in the tests.

## Versions

^12.0.0

**Comment by mdjastrzebski** [comment]
@Niryo I assume that you are referring to `hidden` query option. This option is modelled after web RTL's option of the same name, and it refers to the concept of being `hidden` in terms of accessibility rather than visually hidden. The accessibility mechanism is used to give rendered UI a semantic meaning.

In practical terms we support `display: none` as one of the checks for element being hidden. This is because `display: none` elements are not rendered as native iOS/Android components, they are ignored. Therefore by default user is not expected to notice them. In case of `opacity: 0` however such elements are still rendered as native iOS/Android components, although their opacity makes them "invisible". At the same time these component can receive touch events, and therefore user is still able to interact with them, as well as assistive technology, like screen readers, also can interact with them.

**Comment by Niryo** [comment]
What about `scale:0` ? I don't think you can interact with elements with scale 0 and it's a common trick to hide elements.

**Comment by mdjastrzebski** [comment]
@Niryo I consider 'scale' to be similar to 'opacity' in that regard. It is used to achieve certain visual effect, for which one special value hides the element visually. However, the semantics of this style are about the visual effect (e.g. scaling) and not hiding element from the user.

Recommended workaround would be to set both scale for visual effect, and some of the accessibility props used by RNTL for semantic effect.
