### ISSUE TITLE
Modal onShow not called when visible changes

### ISSUE THREAD

**Issue by dhohmann** [callstack/react-native-testing-library#1393]
Hi all, 

I want to execute some code when a modal is displayed.
Therefore, I added a callback function to the `onShow` property of the modal component.
This works fine when executed in Expo Go or in the real app.

**The problem occurs during tests.** Unfortunately, this callback function does not get executed when the modal shows.

The workaround is to directly call `fireEvent(modal, "show")`.
Is there something I am missing or is this the expected behaviour?

### Test with workaround
```typescript
import { fireEvent, render, waitFor } from "@testing-library/react-native";
import { useState } from "react";
import { Button, Modal } from "react-native"


const ModalTest = (props: { onShow: () => {}, onButtonPress: ()=>{} }) => {
    const [visible, setVisible] = useState(false);

    return (
        <>
            <Button title="show modal" testID="show modal" onPress={() => { props.onButtonPress(); setVisible(true) }} />
            <Modal testID="modal" onShow={props.onShow} visible={visible} />
        </>
    );
}

describe("Modal", () => {
    it("calls onshow", async () => {
        const onShow = jest.fn();
        const onButtonPress = jest.fn();
        const screen = render(<ModalTest onShow={onShow} onButtonPress={onButtonPress}/>);
        const modal = screen.getByTestId("modal");
        fireEvent.press(screen.getByTestId("show modal"));
        expect(onButtonPress).toBeCalled();
        expect(modal).toBeOnTheScreen();
        expect(modal).toHaveProp("visible", true);

        fireEvent(modal, "show"); // <-- workaround
        await waitFor(() => expect(onShow).toBeCalled()); // <-- fails without workaround
    });
});
```

**Comment by mdjastrzebski** [comment]
@dhohmann This is due to fact that RNTL does run only JS part of your application, and native part either does not exist at all or is mocked. More details [here](https://callstack.github.io/react-native-testing-library/docs/testing-env#react-test-renderer).

In case of modal, the [Modal mock](https://github.com/facebook/react-native/blob/b3478cb96d2be4328e3a066de212d1f7095e6475/packages/react-native/jest/mockModal.js) provided by React Native is really simple and only respects for `visible` prop. It does not have any logic to call events like `onShow`.

You should probably fire `onShow` event manually, or you might copy the Modal mock locally and tweak it to your needs, so that it calls `onShow`.

**Comment by dhohmann** [comment]
Thanks for your answer and your time. 
Somehow, I did not find the mock in the RN repo 😓

**Comment by AugustinLF** [comment]
@mdjastrzebski I'm wondering if it wouldn't make sense to try to make those mocks better. I understand that ofc we don't want to rewrite the entire native logic in JS, but I feel that it could be beneficial to handle the main case. But perhaps it's a discussion we should have with the RN team, and contribute back to those mocks.

**Comment by mdjastrzebski** [comment]
@AugustinLF It would be better to fix it in the React Native repo. I would be wary about duplicating official RN mocks, as:
- We have limited dev resources
- Mock should match RN version and not RNTL version.

In case anyone, us or 3rd party, want's to implement it, then it should be a separate repo matching RN versioning. 

BTW that's a cool OSS side project: `react-native-mocks`!
