### ISSUE TITLE
It prevents implementation details

### ISSUE THREAD

**Issue by deepakaggarwal7** [callstack/react-native-testing-library#246]
Hi,

I've two questions:
1) In the introduction page, there's a quote - "But really not any, it prevents you from testing implementation details because we stand this is a very bad practice." 
Could you please help me understand this better? May be any example or reference.
Where to draw a line of what should I unit test with it and not. 

2) Also, in my previous few questions, you always discourage queries by types. What is recommended then - testIds? Want to ensure of following best practices.

thanks

**Comment by thymikee** [comment]
1. testing implementation details would be e.g. modifying internal component state (possible with Enzyme) or querying on that state.
2. I recommend grabbing by text and accessibility queries, because that's what user sees. Using `testID` is the last resort, when you're out of ideas on how to grab something. Querying by type is discouraged, because it may be possible that the user can't see/interact the element (similar to `testID`, invisible to the user). It can be helpful when testing contracts between components though, e.g. checking if certain props were passed from Component1 to Component2 (provided that Component2 is already tested on its own)

I'd avoid using the word "unit test". There's no clear distinction what "unit" is, so it gets counterproductive when discussing something that can be understood in different ways.

**Comment by deepakaggarwal7** [comment]
Thanks for your prompt response (as always). I found an article and a podcast as well from michał-pierzchała explaining the difference. 

I recently had a component where an array rendered with following tree:
<TOUCHABLE1><VIEW1><TETXT1/></VIEW1></TOUCHABLE1>
<TOUCHABLE2><VIEW2><TETXT1/></VIEW2></TOUCHABLE2>
Using getBytText, I could get the text but to press the event I had to do 
getByText(element.parent.parent) to reach touchable. Are these the kind of places where TestID should be used or there's even better solution?
thanks

**Comment by thymikee** [comment]
You don't need to strictly select touchable to press it. The event will bubble to parent components, so pressing on text (as user does) is perfectly fine
