### ISSUE TITLE
flushMicrotasksQueue functionality 

### ISSUE THREAD

**Issue by Kida007** [callstack/react-native-testing-library#265]
Here is a test that intend to check whether loading state is working properly . 
I made it work somehow but i can't understand why and how flushMicroTasksQueue is functioning ?

![image](https://user-images.githubusercontent.com/22558035/76961876-2e145b00-6944-11ea-8a88-863b0e03c3eb.png)

Actual  Flow :
1) on button press 
2) component state changes to {  loading: true } 
3) then API is called (which is failing because i havent mocked api modules)
4) because of Api fail , we set State to  { loading:false }

Now my question is awaitFlushMicroTasksQueue waiting for **setState** to over or Im just getting lucky ?

**Comment by thymikee** [comment]
It will advance your microtask (promises) queue to the next one. You can find a really solid article on that here: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

However, I wouldn't use this API, it's quite brittle and likely works only because you mock your API request to return a promise immediately (in next microtask). What's better is to use `waitForElement`: https://callstack.github.io/react-native-testing-library/docs/api#waitforelement and check if the loading element is gone, or some content showed up.
