### ISSUE TITLE
Compatibility with eslint-plugin-testing-library

### ISSUE THREAD

**Issue by thymikee** [callstack/react-native-testing-library#295]
## Describe the Feature

It would be lovely to verify that our library is compatible with [eslint-plugin-testing-library](https://testing-library.com/docs/ecosystem-eslint-plugin-testing-library), determine what's missing and plan the necessary work to make it usable. 

## Possible Implementations

I'd like avoid creating another plugin based on the existing one. I'd prefer documenting the shortcomings (e.g. lack of `screen` if there are rules for that)

**Comment by thymikee** [comment]
cc @mdjastrzebski

**Comment by thymikee** [comment]
@cross19xx please put your findings here :)

**Comment by cross19xx** [comment]
With the exception of the following syntaxes, all other rules are valid and compatible with `eslint-plugin-testing-library`.

- [`no-debug`](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/no-debug.md): Using the default `debug` is seen as a valid syntax, whereas using the `debug` inside the `render` method is seen as an invalid syntax, i.e.

  ```js
  // Valid syntax
  import {debug} from 'react-native-testing-library';
  debug(<Component />);

  // Invalid syntax
  import {render} from 'react-native-testing-library';
  const {debug} = render(<Component />);
  ```

  Luckily, `react-native-testing-library@next` covers this.

- [`prefer-wait-for`](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/prefer-wait-for.md): This is shown as an invalid syntax the wait method in RNTL is `waitForElement`. A suggestion will be to have an alias for `waitForElement` as `waitFor`. Depending on the state of this (i.e. if on or off), [`no-wait-for-empty-callback`](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/no-wait-for-empty-callback.md) may be triggered

- [`prefer-screen-queries`](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/prefer-screen-queries.md). This will require having a `screen` object.

**Comment by thymikee** [comment]
Thanks! Now w need to document it

**Comment by BatDroid** [comment]
@thymikee could you please explain a bit more about what should be documented. I would love to start my contribution on this repo

**Comment by thymikee** [comment]
> - prefer-screen-queries. This will require having a screen object.

Only this one is relevant now, since we don't have `screen` queries.

**Comment by pierrezimmermannbam** [comment]
I have tried all rules on my project and they all seem to work fine but some are irrelevant : 

- [prefer-screen-queries](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-screen-queries.md) : as stated above, it doesn't make sense without a screen object
- [prefer-user-event](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-user-event.md) : user event is not compatible with rntl
- [no-dom-import](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-dom-import.md) : not so sure about that one but there should be no reason to import dom-testing-library
- [prefer-wait-for](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-wait-for.md): wait is no longer available
- [no-wait-for-empty-callback](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-wait-for-empty-callback.md) : callback is not optional 

consistent-data-testid works but it needs to be configured so that it checks the testID attribute : 

```javascript
{
  "testing-library/consistent-data-testid": [
    2,
    {
      "testIdAttribute": ["testID"],
     "testIdPattern": "^TestId(__[A-Z]*)?$"
    }
  ]
}
```

@thymikee  I 'd be glad to help on the doc, where would you document this ?

**Comment by thymikee** [comment]
We have a Guides section on the website. A new guide called "eslint compatibility" or so would be nice to have.

**Comment by mdjastrzebski** [comment]
Closing as done.
