### ISSUE TITLE
What should we use instead of queryByType?

### ISSUE THREAD

**Issue by morris14** [callstack/react-native-testing-library#336]
We use 'queryByType' to query a react component/object but I can see that will be deprecated in the next release. What's the best way to query a react component/object?

```js
const { queryByType } = render(
  <Provider store={mockStore(mockState)}>
    <CardCarousel cards={cardsArray} />
  </Provider>
);

const cardComponent = queryByType(PlaceholderCard);

// Assert that a component is rendered
expect(!!cardComponent).toBe(true);
```
and
```js
const { queryByType } = render(
  <Provider store={mockStore(mockState)}>
    <CardCarousel cards={cardsArray} />
  </Provider>
);

const cardComponent = queryByType(PlaceholderCard);

// Assert that a component is not rendered
expect(!!cardComponent).toBe(false);
```

**Comment by thymikee** [comment]
`queryByType` is not going anywhere. We're keeping this API but under a different name with `UNSAFE_` prefix: `UNSAFE_queryByType`, so you can still use it. It's generally advised to not use this API unless you have a good reason too (unit testing your components instead of integration testing), so be mindful.

It will all be included in the migration guide we're preparing on the `next` branch, so don't worry :) 

Regarding you example: the `PlaceholderCard` may render `null` and it's still going to be there, while your user wouldn't be able to interact with it. It's generally better to assert on stuff that a user can interact with, like text, accessibility attributes, input values, etc.

**Comment by morris14** [comment]
Many thanks @thymikee !
