### ISSUE TITLE
debug documentation incorrect about returned JSX or misconfiguration?

### ISSUE THREAD

**Issue by tschanz-pcv** [callstack/react-native-testing-library#450]
## Is the Debug documentation wrong about the returned JSX or have I mis-configured by setup?

According to the docs about the [`debug` function](https://callstack.github.io/react-native-testing-library/docs/api#debug) it would suggest that a component which contains `<TouchableOpacity>` would render this as-is and not expand it into `<View>`s.

But the Snapshot and debug output clearly expands all components into `<View>`s. 

Is the documentation wrong or is this configurable?

There is another issue related to this: https://github.com/callstack/react-native-testing-library/issues/156

**Comment by thymikee** [comment]
It's possible that the mock of TouchableOpacity changed since this doc was made. Feel free to send an updated one, based on the results of running something similar with the latest version of React Native. IIRC it is indeed implemented using native `View`s so whatever comes out of the snapshot is correct.

**Comment by thymikee** [comment]
This has been addressed recently, thanks for catching this :)
