### ISSUE TITLE
how to mock component method  

### ISSUE THREAD

**Issue by fangasvsass** [callstack/react-native-testing-library#452]
export default class Demo extends Component {

componentdidmount(){
  this.fetchData()
}

fetchData=()=>{
}
  render() {
    return (
      <View>
        <Text> textInComponent </Text>
      </View>
    )
  }
}

how to mock fetchData check fetchData call times

**Comment by thymikee** [comment]
When your component fetches data, something observable happens, e.g. fetched data is displayed to the user. So, instead of checking of `fetchData` is called, test if this data eventually displayed to the user or whatever is appropriate for this component. For more information on mocking classes, feel free to consult Jest documentation.
