### ISSUE TITLE
Favoring text and accessibility queries instead of testId query

### ISSUE THREAD

**Issue by Kjaer** [callstack/react-native-testing-library#482]
## Why do you asking stopping use of testId query?

I haven't implemented any accessibility to my overall application and contents are very subject to change so my best bet is `testId` queries when it comes to test. Why do you stating use it as escape hatch? Isn't it safe to use any more? I don't get the reason throughly and now hesitating when I am using `testId` queries.

**Comment by thymikee** [comment]
The main reason is that `testID` is invisible to your users, so you may accidentally test something that a user can't interact with. You can also remove the `testID` from a component at some point, leaving the functionality unchanged, and you may end up with a breaking test because `testID` is an implementation detail. 

Be mindful and think like your users when testing your app and you'll be fine using any of the queries.

**Comment by Kjaer** [comment]
Thanks for the reply. 
> think like your users when testing your app
but what about ever changing content for the test subject. Do you now recommending rely on content and update the tests everytime  comply with the content? That sounds like a endless chores adding up in daily work.

**Comment by thymikee** [comment]
We don't do any recommendations here. Use your best judgement.

**Comment by Kjaer** [comment]
Very well. Promoting other queries against `testID` queries sound it to me. But you clearly stated you're not. I wanted to be sure that If I am missing a point. But it's obviously it's matter of how you like to use it.
