### ISSUE TITLE
Getting snapshot after fireEvent

### ISSUE THREAD

**Issue by MaliahRajan** [callstack/react-native-testing-library#570]

**Comment by mdjastrzebski** [comment]
@MaliahRajan you can use [`toJSON()`](https://callstack.github.io/react-native-testing-library/docs/api/#tojson) to generate JSON representation on your component tree. This can be also used after raising events using `fireEvent`. If the component tree change is not synchronous you might have to wait for the results using either: `findBy` queries or `waitFor`.

Note that due to limitations of React Test Renderer you are not able to call `toJSON()` on the result of particular query. You can only call `toJSON()` on `screen` object or use the one returned from `render` method (both of these  approaches are equivalent).
