### ISSUE TITLE
getByText can't find <Text>

### ISSUE THREAD

**Issue by joanca** [callstack/react-native-testing-library#665]
## Describe the bug
I'm trying the most basic example possible of `getByText` query in a component that just renders one `<Text>` component. It can't find the element.

## Expected behavior
It finds the element.

## Steps to Reproduce
Create an empty component that just renders `<Text>text</Text>` and test with `getByText(/text/i)`.

## Screenshots
![image](https://user-images.githubusercontent.com/979527/107137704-c9f8dd80-68ed-11eb-9f51-07d48d14731b.png)

## Versions
```
  npmPackages:
    @testing-library/react-native: ^7.1.0 => 7.1.0
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-test-renderer: ^16.13 => 16.14.0
```

## Extra info
Maybe it has to do with the way I setup the project? you can find the repository here: https://gitlab.com/joanca/rn-playground

Thanks!

**Comment by Tony308** [comment]
Works fine for me. Definitely something not right locally and not issue with repo.
Recommend setting up project using `npx react-native init projectName`; with the same tests and see if the issue persists on a fresh project.

**Comment by MattAgn** [comment]
@lukewlms I think your second example does not work because the queries try to find a perfect match for the text, finding substrings does not work yet. I you have "2MR Plus +" in your component but search for "2MR Plus", it won't find the node. However I don't know how you can search for a font awesome icon in your test.

**Comment by lukewlms** [comment]
@MattAgn I did figure that out afterward - thanks for the confirmation.  My initial expectation was that partial match would work.

**Comment by janithl** [comment]
*bump*

This is a real pain point for someone trying to upgrade from 6.0 as partial matches were working just fine on previous versions.

**Comment by mdjastrzebski** [comment]
Closing issue as stale.

@joanca please report a new GH issue if the problem is present in the current version of RNTL (v11) in the recommended setup as in the [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic). If so, please provide also a minimal repro repository.
