### ISSUE TITLE
Conflicting React version requirements with current react-test-renderer dependency?

### ISSUE THREAD

**Issue by gusbmurphy** [callstack/react-native-testing-library#671]
Hello! I feel that this is a very beginner-level question, but I've just started my second project that I'd like to use the testing library in, and when installing it have run into this NPM error:

```
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.0.0" from @testing-library/react-native@7.1.0
npm ERR!   node_modules/@testing-library/react-native
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-test-renderer@17.0.1
npm ERR! node_modules/react-test-renderer
npm ERR!   peer react-test-renderer@">=16.0.0" from @testing-library/react-native@7.1.0
npm ERR!   node_modules/@testing-library/react-native
```

I've solved this in the past by just using `--legacy-peer-deps` to ignore this, but I'd like to understand better what's going on here. Would it make sense for the `react-test-renderer` dependency to be for any minor update to 16, rather than anything above 16? My understanding is that React-Native 0.63.4 is built for React 16.13.1—although I seem to remember somewhere that version 17 is intentionally not much different than 16 or something along those lines.

**Comment by thymikee** [comment]
We need to keep it under `>=16` as the library is compatible with both React 16 and 17, regardless of React Native version used. When RN 0.64 comes out, which bumps React to 17, we're not gonna change the target to >17 as well, since the latest version of this library is still going to work fine for RN >= 0.60.

The real problem here is npm installing the peer deps by default, which cases the situations like above (easily fixable by manually adding react-test-renderer@16 to your deps). This is one of the reasons there's some push back from the community that this behavior of npm should be opt-in instead of opt-out.

Closing, as wontfix.

**Comment by gusbmurphy** [comment]
Thanks so much for the concise response @thymikee !

**Comment by garymillergit** [comment]
Sorry to post on a closed question but I have the same problem and I don't understand what the solution is. @gusbmurphy can you post your `package.json` (or just the relevant parts) so I can see what versions you're using?

**Comment by gusbmurphy** [comment]
@garymillergit sorry to say but I think I'm at about the same level you are! I've chosen to just go ahead with using `--legacy-peer-deps` like so: `npm install --save-dev @testing-library/react-native --legacy-peer-deps`—having specified a lower `react-test-renderer` version in my `package.json` (16.13.1). I was expecting that adding `"react-test-renderer": "16.13.1"` under `devDependecies` would've prevented that error that I mentioned in the original post, but it did not. So, again, sorry I can't be of more help, I'm still fairly confused but it's now my limited understanding that this is simply not something to worry about!
