### ISSUE TITLE
v8.0.* makes Apollo Mock fails

### ISSUE THREAD

**Issue by eppisapia** [callstack/react-native-testing-library#874]
## Ask your Question

After upgrading to **@testing-library/react-native@8.0.0** or **@testing-library/react-native@8.0.0.rc**, all my spec with Apollo Mocks start to fail, throwing error **TypeError: (0 , _timers.setTimeout) is not a function**

After rendering, I force all the promises to resolve but it's stable, at first it work but sometimes it breaks. Before, 8.0.0 I solved this problem using waitFor but with the v8.0.* waitFor doesn't find any Async callback

```
   await act(async () => {
    await new Promise(resolve => setImmediate(resolve));
  });
  
  expect(getByText("Mock Text")).toBeDefined()
 ```

### Setup

- React v17.0.1
- React Native: 0.64.2
- Jest v26.6.3

### Jest config 

```
const jestPreset = require("react-native/jest-preset");
const { defaults: tsjPreset } = require("ts-jest/presets");

... 
{
  ...tsjPreset,
  "preset": "@testing-library/react-native"
  
  setupFiles: {
     ...jestPreset.setupFiles
  }
}
```

**Comment by mdjastrzebski** [comment]
Closing issue as stale. @eppisapia please report a new GH issue if the problem is present in the current version of RNTL (v11) in recommended setup as in [basic example app](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic). If so, please also provide a repro repository.
