### ISSUE TITLE
getByText fails to get text when using alternate ui lib implementation

### ISSUE THREAD

**Issue by juddey** [callstack/react-native-testing-library#88]
I'm using wix's `react-native-ui-lib` with `react-native-testing-library`. They have extended some core rn elements (eg Text) so that their elements are used instead. Example: https://github.com/wix/react-native-ui-lib/wiki/USAGE

When I use Text element from `react-native-ui-lib`, the getByText helper fails to find the text. However, when I switch to the RN Text component, the tests pass as I expect.

Not sure what the right way forward is here so thought I would log an issue to discuss.

(Right now I'm just using `toJSON` and a string regex to assert that the text was found.)

**Comment by thymikee** [comment]
We're currently only looking for `Text` component exported directly from `react-native`, because looking for strings turned out bad and unreliable. 

It works like this:
https://github.com/callstack/react-native-testing-library/blob/ad61c409e9f5908a746a87ded92dcd0b7736036a/src/helpers/getByAPI.js#L17-L28

We've written this with more platforms in mind, but nothing prevents us adding `Text` from other native libraries (I assume `Text` from `react-native-ui-lib` doesn't use `Text` from `react-native`, because that should work).

There's an `options` parameter to the `render` fn that we could utilize to do this, e.g. by adding `TextComponent` option:
```js
import {Text} from 'react-native-ui-lib';
import {render as RNTLrender} from 'react-native-testing-library';

const render = (component, options) => {
  return RNTLrender(component, {...options, TextComponent: Text})
};
export render;
```

**Comment by juddey** [comment]
Well, I managed to fork and clone the repo today to have a go at this, but thats as far as I got. More tomorrow!

**Comment by juddey** [comment]
> I assume Text from react-native-ui-lib doesn't use Text from react-native, because that should work.

rn-ui-lib _does_ use the react native text component, and it always has. https://z448401921.github.io/react-native-ui-lib/uilib-docs/public/docs/Text/

However, I've upgraded to `1.5` and now the tests are passing, so something must have happened in the interim. :tada: 

Given this, and the fact most ui-libs would probably extend from react-native, I'll close off this issue now. Feel free to re-open if I have the wrong end of the stick.
