### ISSUE TITLE
Act error message on alone `render(<Component/>)`

### ISSUE THREAD

**Issue by downloadpizza** [callstack/react-native-testing-library#927]
## Describe the bug

I have a basically empty testcases (only tries to render) and it tells me I should be using act.

## Expected behavior

It should not, or I am abusing react-native itself, not sure.

## Steps to Reproduce

I have this component:
```js
import React from 'react';
import { useEffect, useState } from "react";

const somePromise = async() => true;

const MRA = () => {
  const [someState, setSomeState] = useState();

  const onSomePromiseResolves = (spv) => setSomeState(spv);

  useEffect(() => {
    somePromise().then(onSomePromiseResolves)
  }, []);

  return (<></>);
}

export default MRA;
```

With this testcase:
```js
import React from 'react';

import { render } from "@testing-library/react-native";
import MRA from "../Pages/MRA";

it('runs', () => {
  render(<MRA/>);
});
```

I get the following error:
```
  console.error
    Warning: An update to MRA inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at MRA (/home/downloadpizza/git-repositories/ilving-app/Pages/MRA.js:7:37)

       7 |   const [someState, setSomeState] = useState();
       8 |
    >  9 |   const onSomePromiseResolves = (spv) => setSomeState(spv);
         |                                          ^
      10 |
      11 |   useEffect(() => {
      12 |     somePromise().then(onSomePromiseResolves)

      at printWarning (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:68:30)
      at error (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:44:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15034:9)
      at setSomeState (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7129:9)
      at onSomePromiseResolves (Pages/MRA.js:9:42)
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15
```

## Versions

 npmPackages:
    @testing-library/react-native: ^9.0.0 => 9.0.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-test-renderer: 17.0.2 => 17.0.2

**Comment by pierrezimmermannbam** [comment]
Hello @downloadpizza, it is in fact normal that you get this warning. What happens is that the state update on someState is not wrapped in act since it happens after the end of your test. This is an issue for several reasons, namely because you're not testing the component as the end user would see it since you're not awaiting for promises to be resolved. Testing a page before the data has loaded makes little sense because the user starts interacting with the page once it's loaded, so your tests should follow the same logic. This is explained more in detail in this [article](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning) from Kent C. Dodds. 

To fix this, your test needs to be asynchronous and you need to use the waitFor util and wait for something that will be true once the state has changed. For instance, if someState is a loading state that is set to false after some data is fetched, you'll need to wait for either the data to be displayed or the loader to be removed

```javascript
await waitForElementToBeRemoved(() => getByTestId('loader'));
```

or 

```javascript
await waitFor(() => {
   expect(getByText('data')).toBeTruthy();
});
```

**Comment by AugustinLF** [comment]
As answer above, this is the expected behaviour, and is actually linked to the way the React itself is implemented. We could however see if there's a way to improve error messages on our end (even though react's error message does point to the docs).

If you do see another possible behaviour, please let us know and we'll see if we can change the way our API works to better support your use case.

**Comment by mdjastrzebski** [comment]
@dvijeniii05 From your comment I assume you are getting some `act` warning and connect it to your component structure of Parent/Child. In general `act` warnings are not related to component structure, but rather to the timing of React updates. In basic cases RNTL applies `act` for you (`render`, `fireEvent`, etc) BUT if you have re-renders based e.g. on `setTimeout` then you need to either use relevant function `waitFor`/`findBy*` OR use `act` directly.

You can learn more about these in [our docs](https://callstack.github.io/react-native-testing-library/docs/understanding-act).

**Comment by pierrezimmermannbam** [comment]
@dvijeniii05 the simplest solution would be to directly test the child you're interested about. If you're testing the parent then it should be tested as a whole. in some case it makes sense to test the parent, e.g. making a snapshot of a page or if several children interact with each other. If not, then testing the child in isolation should solve your issue

**Comment by pierrezimmermannbam** [comment]
There is no generic solution for that problem I think. If any API call is made by the component under test then you should wait for it to have finished, even if you don't really care about that component. A solution would be to build a custom render function for that component that would mock api calls and wait for api calls to be over and then use that util function in every test


```tsx
const renderMyPage = async () => {
  // mock api calls
   render(<MyPage/>);

  expect(await screen.findByText('data')).toBeOnTheScreen();
}


// in test
await renderMyPage();
```

There are reasons why it's important to wait for the asynchronous code in any case. The first is that you want to test from the user's perspective and users usually will interact with your app once promises are resolved. The other is that there may be other stuff that you didn't think about that would occur after your expectation and that would cause an error

**Comment by mdjastrzebski** [comment]
@dvijeniii05 You have to options:

1. Either make a helper function that would contain `waitFor`/`findBy` call for data-driven component and add it to the end of each of your tests. That way you would simply invoke common helper instead of duplicating complex `waitFor`/`findBy` check.

2. Or prevent your parent component from rendering the data-driven component in cases when you are not interested in it. Either by introducing some extra props, mocking that particular component, etc.
