### ISSUE TITLE
Vscode Intellisense making incorrect package imports for RNTL

### ISSUE THREAD

**Issue by charlestbell** [callstack/react-native-testing-library#959]
## Describe the bug

When I use RNTL in Vscode, it offers Intellisense for queries. (getByText, queryByPlaceholderText, etc) 

The problem is, if I use what's offered by Intellisense, it adds an import automatically from /dom. 

This throws an error when you try to run the tests and it's usually not obvious what's happening. 

## Expected behavior

When I use Intellisense in Vscode with RNTL, it imports queries correctly, or not at all.
- or throw a more helpful console error when this happens.

## Steps to Reproduce

- Use RNTL in Vscode.
- Ensure the file name ends in .test.js

## Screenshots
![Before improper import](https://user-images.githubusercontent.com/54514092/165143343-a66a80b6-a1a6-43fb-bc48-1021545c2f43.jpg)
![After improper import](https://user-images.githubusercontent.com/54514092/165143393-a79f59da-ea27-4982-8e5d-2432600a698a.jpg)
![Correct import](https://user-images.githubusercontent.com/54514092/165143444-29adc89e-12a2-4024-bcf2-4a78548ba7bb.jpg)

## Versions

  npmPackages:
    @testing-library/react-native: ^8.0.0 => 8.0.0 
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-test-renderer: ~17 => 17.0.2

edit: spelling

**Comment by thymikee** [comment]
Hey! In RNTL queries are returned by the `render` function, as you already noticed, so the intellisense will work when you're in its scope. We don't offer top-level imports for queries (same as React Testing Library, although they have `screen` object which helps). Seems that you also have `@testing-library/dom` installed in your project and that's why VSCode fetches these. There's nothing we can do about it really.

**Comment by charlestbell** [comment]
Thanks @thymikee, I had a feeling that might be the answer.

I removed testing-library/dom for the time being and that didn't seem to break anything.
