### ISSUE TITLE
The method `fireEvent.changeText` doesn't "work" and the doc is not clear about it

### ISSUE THREAD

**Issue by GleidsonDaniel** [callstack/react-native-testing-library#978]
## Describe the bug

The function works, but it doesn't work as "expected".

If you go into the doc now and see the example of how to use the `fireEvent.changeText` method [link](https://callstack.github.io/react-native-testing-library/docs/api/#fireeventchangetext-element-reacttestinstance-data-arrayany--void), you will have a function and it will assume that the changeText will change the input `value`.
But that's not what happens and even the tests that the lib has [link](https://github.com/callstack/react-native-testing-library/blob/16bb83c78a1d8b2479f694443ee69c6304be9906/src/__tests__/fireEvent.test.tsx#L146), don't test if the `value` was changed, but if the function was called.
And that doesn't make the slightest sense, if I test an input for example that has a mask, I want to test the value of that the input will return to me and not test whether this method was called or not.

## Expected behavior

That the `fireEvent.changeText` method changes the `value`, or that the documentation is clear that it is not possible to change the `value` and recover the changed `value` for some specific reason.

## Steps to Reproduce

In the `fireEvent.changeText` test [link](https://github.com/callstack/react-native-testing-library/blob/16bb83c78a1d8b2479f694443ee69c6304be9906/src/__tests__/fireEvent.test.tsx#L146) add a debug that will see that the `value` will not be changed.

**Comment by mdjastrzebski** [comment]
As far as I know, you typically use [`TextInput`](https://reactnative.dev/docs/handling-text-input) as a [controlled component](https://reactjs.org/docs/forms.html#controlled-components), i.e. your component using `TextInput` is holding current `value` `for `TextInput` it its state:

```
function Component() {
  const [name, setName] = React.useState('');
  return (
    <TextInput
      testID="input"
      value={name}
      onChangeText={(text) => setName(text)}
    />
  );
}
```

In such case, triggering `fireEvent.changeText` should call your `onChangeText` event handler, which should update the state used for `value` field.

```
test('text input', () => {
  const screen = render(<Component />);
  const textInput = screen.getByTestId('input');
  fireEvent.changeText(textInput, 'Hello');
  expect(textInput.props.value).toBe('Hello');
});
```

Obviously if you do not have a state that is driving `value` prop for `TextInput`, then you cannot observe `value` prop change. But this is not related to RNTL but rather your component code.

Regarding uncontrolled components, where control value would be managed by native code, we do not support that because RNTL simulates only JS part of React Native and not the native part. See [more details](https://callstack.github.io/react-native-testing-library/docs/faq).

**Comment by mdjastrzebski** [comment]
Closing as won't fix.

From my understanding `fireEvent.changeText` work correctly for controlled components, and we do not support uncontrolled components scenario because RNTL does not have a native part.
